from monosim.cell import Cell, Road, Utility, Station

game_board = [
    Cell(kwargs = {
        'name': 'go',
        'type': 'go',
    }),
    Road(kwargs = {
        'name': 'old kent road',
        'type': 'road',
        'price': 60,
        'rent': 2,
        'rent_with_color_set': 4,
        'rent_with_1_houses_0_hotels': 10,
        'rent_with_2_houses_0_hotels': 30,
        'rent_with_3_houses_0_hotels': 90,
        'rent_with_4_houses_0_hotels': 160,
        'rent_with_4_houses_1_hotels': 250,
        'mortgage_value': 30,
        'unmortgage_value': 33,
        'houses_cost': 50,
        'hotels_cost': 50,
        'color': 'brown',
        'board_num': 1,
        'belongs_to': None,
        'is_mortgaged': False
    }),
    Cell(kwargs = {
        'name': 'community chest',
        'type': 'community chest',
    }),
    Road(kwargs = {
        'name': 'whitechapel road',
        'type': 'road',
        'price': 60,
        'rent': 4,
        'rent_with_color_set': 8,
        'rent_with_1_houses_0_hotels': 20,
        'rent_with_2_houses_0_hotels': 60,
        'rent_with_3_houses_0_hotels': 180,
        'rent_with_4_houses_0_hotels': 320,
        'rent_with_4_houses_1_hotels': 450,
        'mortgage_value': 30,
        'unmortgage_value': 33,
        'houses_cost': 50,
        'hotels_cost': 50,
        'color': 'brown',
        'board_num': 3,
        'belongs_to': None,
        'is_mortgaged': False
    }),
    Cell(kwargs = {
        'name': 'income tax',
        'type': 'tax',
    }),
    Station(kwargs = {
        'name': 'kings cross station',
        'type': 'station',
        'price': 200,
        'rent': 25,
        'mortgage_value': 100,
        'unmortgage_value': 110,
        'board_num': 5,
        'belongs_to': None,
        'is_mortgaged': False
    }),
    Road(kwargs = {
        'name': 'the angel islington',
        'type': 'road',
        'price': 100,
        'rent': 6,
        'rent_with_color_set': 12,
        'rent_with_1_houses_0_hotels': 30,
        'rent_with_2_houses_0_hotels': 90,
        'rent_with_3_houses_0_hotels': 270,
        'rent_with_4_houses_0_hotels': 400,
        'rent_with_4_houses_1_hotels': 550,
        'mortgage_value': 50,
        'unmortgage_value': 55,
        'houses_cost': 50,
        'hotels_cost': 50,
        'color': 'light_blue',
        'board_num': 6,
        'belongs_to': None,
        'is_mortgaged': False
    }),
    Cell(kwargs = {
        'name': 'chance',
        'type': 'chance',
    }),
    Road(kwargs = {
        'name': 'euston road',
        'type': 'road',
        'price': 100,
        'rent': 6,
        'rent_with_color_set': 12,
        'rent_with_1_houses_0_hotels': 30,
        'rent_with_2_houses_0_hotels': 90,
        'rent_with_3_houses_0_hotels': 270,
        'rent_with_4_houses_0_hotels': 400,
        'rent_with_4_houses_1_hotels': 550,
        'mortgage_value': 50,
        'unmortgage_value': 55,
        'houses_cost': 50,
        'hotels_cost': 50,
        'color': 'light_blue',
        'board_num': 8,
        'belongs_to': None,
        'is_mortgaged': False
    }),
    Road(kwargs = {
        'name': 'pentonville road',
        'type': 'road',
        'price': 120,
        'rent': 8,
        'rent_with_color_set': 16,
        'rent_with_1_houses_0_hotels': 40,
        'rent_with_2_houses_0_hotels': 100,
        'rent_with_3_houses_0_hotels': 300,
        'rent_with_4_houses_0_hotels': 450,
        'rent_with_4_houses_1_hotels': 600,
        'mortgage_value': 60,
        'unmortgage_value': 66,
        'houses_cost': 50,
        'hotels_cost': 50,
        'color': 'light_blue',
        'board_num': 9,
        'belongs_to': None,
        'is_mortgaged': False
    }),
    Cell(kwargs = {
        'name': 'jail',
        'type': 'jail',
    }),
    Road(kwargs = {
        'name': 'pall mall',
        'type': 'road',
        'price': 140,
        'rent': 10,
        'rent_with_color_set': 20,
        'rent_with_1_houses_0_hotels': 50,
        'rent_with_2_houses_0_hotels': 150,
        'rent_with_3_houses_0_hotels': 450,
        'rent_with_4_houses_0_hotels': 625,
        'rent_with_4_houses_1_hotels': 750,
        'mortgage_value': 70,
        'unmortgage_value': 77,
        'houses_cost': 100,
        'hotels_cost': 100,
        'color': 'purple',
        'board_num': 11,
        'belongs_to': None,
        'is_mortgaged': False
    }),
    Utility(kwargs = {
        'name': 'Electric company',
        'type': 'utility',
        'price': 150,
        'rent': None,  # utility's rent depends of dice value
        'mortgage_value': 75,
        'unmortgage_value': 83,
        'board_num': 12,
        'belongs_to': None,
        'is_mortgaged': False
    }),
    Road(kwargs = {
        'name': 'whitehall',
        'type': 'road',
        'price': 140,
        'rent': 10,
        'rent_with_color_set': 20,
        'rent_with_1_houses_0_hotels': 50,
        'rent_with_2_houses_0_hotels': 150,
        'rent_with_3_houses_0_hotels': 450,
        'rent_with_4_houses_0_hotels': 625,
        'rent_with_4_houses_1_hotels': 750,
        'mortgage_value': 70,
        'unmortgage_value': 77,
        'houses_cost': 100,
        'hotels_cost': 100,
        'color': 'purple',
        'board_num': 13,
        'belongs_to': None,
        'is_mortgaged': False
    }),
    Road(kwargs = {
        'name': 'northumberland avenue',
        'type': 'road',
        'price': 160,
        'rent': 12,
        'rent_with_color_set': 24,
        'rent_with_1_houses_0_hotels': 60,
        'rent_with_2_houses_0_hotels': 180,
        'rent_with_3_houses_0_hotels': 500,
        'rent_with_4_houses_0_hotels': 700,
        'rent_with_4_houses_1_hotels': 900,
        'mortgage_value': 80,
        'unmortgage_value': 88,
        'houses_cost': 100,
        'hotels_cost': 100,
        'color': 'purple',
        'board_num': 14,
        'belongs_to': None,
        'is_mortgaged': False
    }),
    Station(kwargs = {
        'name': 'marylebone station',
        'type': 'station',
        'price': 200,
        'rent': 25,
        'mortgage_value': 100,
        'unmortgage_value': 110,
        'board_num': 15,
        'belongs_to': None,
        'is_mortgaged': False
    }),
    Road(kwargs = {
        'name': 'bow street',
        'type': 'road',
        'price': 180,
        'rent': 14,
        'rent_with_color_set': 28,
        'rent_with_1_houses_0_hotels': 70,
        'rent_with_2_houses_0_hotels': 200,
        'rent_with_3_houses_0_hotels': 550,
        'rent_with_4_houses_0_hotels': 750,
        'rent_with_4_houses_1_hotels': 950,
        'mortgage_value': 90,
        'unmortgage_value': 99,
        'houses_cost': 100,
        'hotels_cost': 100,
        'color': 'orange',
        'board_num': 16,
        'belongs_to': None,
        'is_mortgaged': False
    }),
    Cell(kwargs = {
        'name': 'community chest',
        'type': 'community chest',
    }),
    Road(kwargs = {
        'name': 'marlborough street',
        'type': 'road',
        'price': 180,
        'rent': 14,
        'rent_with_color_set': 28,
        'rent_with_1_houses_0_hotels': 70,
        'rent_with_2_houses_0_hotels': 200,
        'rent_with_3_houses_0_hotels': 550,
        'rent_with_4_houses_0_hotels': 750,
        'rent_with_4_houses_1_hotels': 950,
        'mortgage_value': 90,
        'unmortgage_value': 99,
        'houses_cost': 100,
        'hotels_cost': 100,
        'color': 'orange',
        'board_num': 18,
        'belongs_to': None,
        'is_mortgaged': False
    }),
    Road(kwargs = {
        'name': 'vine street',
        'type': 'road',
        'price': 200,
        'rent': 16,
        'rent_with_color_set': 32,
        'rent_with_1_houses_0_hotels': 80,
        'rent_with_2_houses_0_hotels': 220,
        'rent_with_3_houses_0_hotels': 600,
        'rent_with_4_houses_0_hotels': 800,
        'rent_with_4_houses_1_hotels': 1000,
        'mortgage_value': 100,
        'unmortgage_value': 110,
        'houses_cost': 100,
        'hotels_cost': 100,
        'color': 'orange',
        'board_num': 19,
        'belongs_to': None,
        'is_mortgaged': False
    }),
    Cell(kwargs = {
        'name': 'free parking',
        'type': 'free parking',
    }),
    Road(kwargs = {
        'name': 'strand',
        'type': 'road',
        'price': 220,
        'rent': 18,
        'rent_with_color_set': 36,
        'rent_with_1_houses_0_hotels': 90,
        'rent_with_2_houses_0_hotels': 250,
        'rent_with_3_houses_0_hotels': 700,
        'rent_with_4_houses_0_hotels': 875,
        'rent_with_4_houses_1_hotels': 1050,
        'mortgage_value': 110,
        'unmortgage_value': 121,
        'houses_cost': 150,
        'hotels_cost': 150,
        'color': 'red',
        'board_num': 21,
        'belongs_to': None,
        'is_mortgaged': False
    }),
    Cell(kwargs = {
        'name': 'chance',
        'type': 'chance',
    }),
    Road(kwargs = {
        'name': 'fleet street',
        'type': 'road',
        'price': 220,
        'rent': 18,
        'rent_with_color_set': 36,
        'rent_with_1_houses_0_hotels': 90,
        'rent_with_2_houses_0_hotels': 250,
        'rent_with_3_houses_0_hotels': 700,
        'rent_with_4_houses_0_hotels': 875,
        'rent_with_4_houses_1_hotels': 1050,
        'mortgage_value': 110,
        'unmortgage_value': 121,
        'houses_cost': 150,
        'hotels_cost': 150,
        'color': 'red',
        'board_num': 23,
        'belongs_to': None,
        'is_mortgaged': False
    }),
    Road(kwargs = {
        'name': 'trafalgar square',
        'type': 'road',
        'price': 240,
        'rent': 20,
        'rent_with_color_set': 40,
        'rent_with_1_houses_0_hotels': 100,
        'rent_with_2_houses_0_hotels': 300,
        'rent_with_3_houses_0_hotels': 750,
        'rent_with_4_houses_0_hotels': 925,
        'rent_with_4_houses_1_hotels': 1100,
        'mortgage_value': 120,
        'unmortgage_value': 132,
        'houses_cost': 150,
        'hotels_cost': 150,
        'color': 'red',
        'board_num': 24,
        'belongs_to': None,
        'is_mortgaged': False
    }),
    Station(kwargs = {
        'name': 'Fenchurch st. station',
        'type': 'station',
        'price': 200,
        'rent': 25,
        'mortgage_value': 100,
        'unmortgage_value': 110,
        'board_num': 25,
        'belongs_to': None,
        'is_mortgaged': False
    }),
    Road(kwargs = {
        'name': 'leicester square',
        'type': 'road',
        'price': 260,
        'rent': 22,
        'rent_with_color_set': 44,
        'rent_with_1_houses_0_hotels': 110,
        'rent_with_2_houses_0_hotels': 330,
        'rent_with_3_houses_0_hotels': 800,
        'rent_with_4_houses_0_hotels': 975,
        'rent_with_4_houses_1_hotels': 1150,
        'mortgage_value': 130,
        'unmortgage_value': 143,
        'houses_cost': 150,
        'hotels_cost': 150,
        'color': 'yellow',
        'board_num': 26,
        'belongs_to': None,
        'is_mortgaged': False
    }),
    Road(kwargs = {
        'name': 'coventry street',
        'type': 'road',
        'price': 260,
        'rent': 22,
        'rent_with_color_set': 44,
        'rent_with_1_houses_0_hotels': 110,
        'rent_with_2_houses_0_hotels': 330,
        'rent_with_3_houses_0_hotels': 800,
        'rent_with_4_houses_0_hotels': 975,
        'rent_with_4_houses_1_hotels': 1150,
        'mortgage_value': 130,
        'unmortgage_value': 143,
        'houses_cost': 150,
        'hotels_cost': 150,
        'color': 'yellow',
        'board_num': 27,
        'belongs_to': None,
        'is_mortgaged': False
    }),
    Utility(kwargs = {
        'name': 'water works',
        'type': 'utility',
        'price': 150,
        'rent': None,  # utility's rent depends of dice value
        'mortgage_value': 75,
        'unmortgage_value': 83,
        'board_num': 28,
        'belongs_to': None,
        'is_mortgaged': False
    }),
    Road(kwargs = {
        'name': 'piccadilly',
        'type': 'road',
        'price': 280,
        'rent': 24,
        'rent_with_color_set': 48,
        'rent_with_1_houses_0_hotels': 120,
        'rent_with_2_houses_0_hotels': 360,
        'rent_with_3_houses_0_hotels': 850,
        'rent_with_4_houses_0_hotels': 1025,
        'rent_with_4_houses_1_hotels': 1200,
        'mortgage_value': 140,
        'unmortgage_value': 154,
        'houses_cost': 150,
        'hotels_cost': 150,
        'color': 'yellow',
        'board_num': 29,
        'belongs_to': None,
        'is_mortgaged': False
    }),
    Cell(kwargs = {
        'name': 'go to jail',
        'type': 'go to jail',
    }),
    Road(kwargs = {
        'name': 'regent street',
        'type': 'road',
        'price': 300,
        'rent': 26,
        'rent_with_color_set': 52,
        'rent_with_1_houses_0_hotels': 130,
        'rent_with_2_houses_0_hotels': 390,
        'rent_with_3_houses_0_hotels': 900,
        'rent_with_4_houses_0_hotels': 1100,
        'rent_with_4_houses_1_hotels': 1275,
        'mortgage_value': 150,
        'unmortgage_value': 165,
        'houses_cost': 200,
        'hotels_cost': 200,
        'color': 'green',
        'board_num': 31,
        'belongs_to': None,
        'is_mortgaged': False
    }),
    Road(kwargs = {
        'name': 'oxford street',
        'type': 'road',
        'price': 300,
        'rent': 26,
        'rent_with_color_set': 52,
        'rent_with_1_houses_0_hotels': 130,
        'rent_with_2_houses_0_hotels': 390,
        'rent_with_3_houses_0_hotels': 900,
        'rent_with_4_houses_0_hotels': 1100,
        'rent_with_4_houses_1_hotels': 1275,
        'mortgage_value': 150,
        'unmortgage_value': 165,
        'houses_cost': 200,
        'hotels_cost': 200,
        'color': 'green',
        'board_num': 32,
        'belongs_to': None,
        'is_mortgaged': False
    }),
    Cell(kwargs = {
        'name': 'community chest',
        'type': 'community chest',
    }),
    Road(kwargs = {
        'name': 'bond street',
        'type': 'road',
        'price': 320,
        'rent': 28,
        'rent_with_color_set': 56,
        'rent_with_1_houses_0_hotels': 150,
        'rent_with_2_houses_0_hotels': 450,
        'rent_with_3_houses_0_hotels': 1000,
        'rent_with_4_houses_0_hotels': 1200,
        'rent_with_4_houses_1_hotels': 1400,
        'mortgage_value': 160,
        'unmortgage_value': 176,
        'houses_cost': 200,
        'hotels_cost': 200,
        'color': 'green',
        'board_num': 34,
        'belongs_to': None,
        'is_mortgaged': False
    }),
    Station(kwargs = {
        'name': 'liverpool st station',
        'type': 'station',
        'price': 200,
        'rent': 25,
        'mortgage_value': 100,
        'unmortgage_value': 110,
        'board_num': 35,
        'belongs_to': None,
        'is_mortgaged': False
    }),
    Cell(kwargs = {
        'name': 'chance',
        'type': 'chance',
    }),
    Road(kwargs = {
        'name': 'park lane',
        'type': 'road',
        'price': 350,
        'rent': 35,
        'rent_with_color_set': 70,
        'rent_with_1_houses_0_hotels': 175,
        'rent_with_2_houses_0_hotels': 500,
        'rent_with_3_houses_0_hotels': 1100,
        'rent_with_4_houses_0_hotels': 1300,
        'rent_with_4_houses_1_hotels': 1500,
        'mortgage_value': 175,
        'unmortgage_value': 193,
        'houses_cost': 200,
        'hotels_cost': 200,
        'color': 'blue',
        'board_num': 37,
        'belongs_to': None,
        'is_mortgaged': False
    }),
    Cell(kwargs = {
        'name': 'super tax',
        'type': 'tax',
    }),
    Road(kwargs = {
        'name': 'mayfair',
        'type': 'road',
        'price': 400,
        'rent': 50,
        'rent_with_color_set': 100,
        'rent_with_1_houses_0_hotels': 200,
        'rent_with_2_houses_0_hotels': 600,
        'rent_with_3_houses_0_hotels': 1400,
        'rent_with_4_houses_0_hotels': 1700,
        'rent_with_4_houses_1_hotels': 2000,
        'mortgage_value': 200,
        'unmortgage_value': 220,
        'houses_cost': 200,
        'hotels_cost': 200,
        'color': 'blue',
        'board_num': 39,
        'belongs_to': None,
        'is_mortgaged': False
    }),
]


def get_properties():
    raise NotImplementedError


def get_color_to_house_mapping():
    from collections import defaultdict

    dict_color_to_house_mapping = defaultdict(list)
    max_name_len = 0

    for c in game_board:
        if len(c.name) > max_name_len:
            max_name_len = len(c.name)
        if c.type == 'road':
            dict_color_to_house_mapping[c.color].append(c)

    print(f"INFO: {max_name_len=}")
    return dict_color_to_house_mapping


from monosim.cards import Card, Deck

def get_community_chest_cards():

    return Deck('community chest', [
        Card("stock_sale", "from sale of stock you get 50.", pay_bank=-50),
        Card("birthday", "it's your birthday. collect 10 from each player.", pay_each_player = -10),
        Card("holiday_fund", "holiday fund matures. collect 100", pay_bank=-100),
        Card("hospital_fees", "hospital fees. pay 100.", pay_bank=100),
        Card("second_price", "you have won second prize in a beauty contest. collect 100", pay_bank=-100),
        Card("school_fees", "school fees. pay 50.", pay_bank=-50),
        Card("jail", "go to jail. go directly to jail. do not pass go. do not collect 200.", action='go_to_jail'),
        Card("inherit", "you inherit 100.", pay_bank=-100),
        Card("consultancy", "collect 25 consultancy fee.", pay_bank=-25),
        Card("income_tax", "income tax refund. collect 20.", pay_bank=-20),
        Card("insurance", "life insurance matures. collect 100.", pay_bank=-100),
        Card("bank_error", "bank error in your favour. collect 200.", pay_bank=-200),
        Card("doctor_fees", "doctor's fees. pay 50.", pay_bank=-50),
        Card("to_go", "advance to go. collect 200.", go_to = 0),
        Card("street_repair", "you are assessed for street repairs: pay 40 per house and 115 per hotel you own.", street_repairs=(40,115)),
        Card("out_of_jail", "get out of jail free. this card may be kept until needed, traded or sold.", action='chance_jail_card', uses_left = 1),
    ])

def get_chance_cards():
    return Deck('chance deck', [
        # classicedition
        Card("out_of_jail", "GET OUT OF JAIL FREE. This card may be kept until needed or traded.", action = 'chance_jail_card', uses_left = 1),
        Card("general_repairs", "Make General Repairs on All Your Property. For each house pay $25. For each hotel $100.", street_repairs = (25, 100)),
        Card("speeding", "Speeding fine $15.", pay_bank = 15),
        Card("election", "You have been elected chairman of the board. Pay each player $50.", pay_each_player = 50),
        Card("back 3 spaces", "Go back three spaces.", advance = -3 ),
        Card("advance_to_utility", "ADVANCE TO THE NEAREST UTILITY. IF UNOWNED, you may buy it from the Bank. IF OWNED, throw dice and pay owner a total ten times the amount thrown.", advanceToNearest = 'utility' ),
        Card("dividend", "Bank pays you dividend of $50.", pay_bank = -50),
        Card("advance_to_railroad", "ADVANCE TO THE NEAREST RAILROAD. If UNOWNED, you may buy it from the Bank. If OWNED, pay owner twice the rental to which they are otherwise entitled.", advanceToNearest= 'station' ), # TODO
        Card("ppor_tax", "Pay poor tax of $15.", pay_bank = -15),
        Card("goto_reading_rail", "Take a trip to Reading Rail Road. If you pass \"GO\" collect $200.", go_to = 5),
        Card("advance", "ADVANCE to Boardwalk.", go_to = 39),
        Card("advance", "ADVANCE to Illinois Avenue. If you pass \"GO\" collect $200.", go_to = 24),
        Card("loan_matures", "Your building loan matures. Collect $150.", pay_bank = -150),
        Card("advance_to_railroad", "ADVANCE TO THE NEAREST RAILROAD. If UNOWNED, you may buy it from the Bank. If OWNED, pay owner twice the rental to which they are otherwise entitled.", advanceToNearest = 'station' ),  # TODO
        Card("advance", "ADVANCE to St. Charles Place. If you pass \"GO\" collect $200.", go_to = 11),
        Card("go_to_jail", "Go to Jail. Go Directly to Jail. Do not pass \"GO\". Do not collect $200.", action = 'go_to_jail' ),
        # new"", yorkcityedition
        Card("chance_jail_card", "Get out of Jail free. This card may be kept until needed or sold.", action = 'chance_jail_card', uses_left = 1 ),
        Card("street_repairs", "Make general repairs on all your property. For each house pay $25. For each hotel $100.", street_repairs = ( 25, 100 )),
        Card("poor_tax", "Pay poor tax of $15.", pay_bank = 15),
        Card("election", "You have been elected chairman of Con Edison. Pay each player $50.", pay_each_player = 50 ),
        Card("back_3_spaces", "Go back 3 spaces.", advance = -3),
        Card("", "Advance token to the nearest Con Edison utility. If UNOWNED you may buy it from the bank. If OWNED, throw dice and pay owner a total of ten times the amount thrown.", advanceToNearest = 'utility' ),   # TODO
        Card("interest", "Citibank pays you interest of $50.", pay_bank = -50),
        Card("advance_to_railroad", "Advance token to the nearest Transportation and pay owner Twice the Rental to which they are otherwise entitled. If Transportation is unowned, you may buy it from the Bank.", advanceToNearest = 'station' ),  # TODO
        #Card("essex_walk", "Take a walk past The Essex House. Advance to GO. Collect $200.", 'advance', 0,32), # TODO
        Card("regency_ride", "Take a ride to the Regency Hotel! If you pass GO collect $200.", go_to = 31),
        Card("fifth_avenue", "Take a walk on fifth avenue. Advance token to Trump Tower.", go_to = 39),
        Card("advance_to_13", "Advance to thirteen.", go_to = 13),
        Card("mutual_funds", "Your Smith Barney mutual fund pays dividend. Collect $150.", pay_bank = -150),
        Card("advance_to_railroad", "Advance token to the nearest Transportation and pay owner Twice the Rental to which they are otherwise entitled.\n\nIf Transportation is unowned, you may buy it from the Bank.", advanceToNearest = 'station'),    # TODO
        Card("central_park", "Catch a bus to Central Park. If you pass GO, collect $200.", go_to =  9),
        Card("go_to_jail", "Go directly to Jail. Do not pass GO, do not collect $200.", action = 'go_to_jail' ),
    ])
